// <auto-generated />
using CRUDLoja.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDLoja.Migrations
{
    [DbContext(typeof(AppDB))]
    partial class AppDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("CRUDLoja.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Futebol"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Alimentos"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Roupas"
                        });
                });

            modelBuilder.Entity("CRUDLoja.Models.CategoriaProduto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("ProdutoId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("CategoriaProdutos");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            CategoriaId = 1,
                            Id = 0
                        },
                        new
                        {
                            ProdutoId = 2,
                            CategoriaId = 1,
                            Id = 0
                        },
                        new
                        {
                            ProdutoId = 3,
                            CategoriaId = 2,
                            Id = 0
                        },
                        new
                        {
                            ProdutoId = 4,
                            CategoriaId = 3,
                            Id = 0
                        });
                });

            modelBuilder.Entity("CRUDLoja.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<double>("Preco")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Bola",
                            Preco = 20.0
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Chuteira",
                            Preco = 35.0
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Biscoito",
                            Preco = 5.0
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Bermuda",
                            Preco = 13.0
                        });
                });

            modelBuilder.Entity("CRUDLoja.Models.CategoriaProduto", b =>
                {
                    b.HasOne("CRUDLoja.Models.Categoria", "Categoria")
                        .WithMany("CategoriaProdutos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRUDLoja.Models.Produto", "Produto")
                        .WithMany("CategoriaProdutos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("CRUDLoja.Models.Categoria", b =>
                {
                    b.Navigation("CategoriaProdutos");
                });

            modelBuilder.Entity("CRUDLoja.Models.Produto", b =>
                {
                    b.Navigation("CategoriaProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
